Alexander Beckwith

Math 855 - Prob w/ Applications

HW5


In [2]:
import numpy as np

# Chapter 3: Problems 1(b), 9(a,b), 17(c), 18(a,b,c,d), 20, 44, 46, 47, 50 and 60.

In [6]:
# problem 1
axes = {"x": 0, "y": 1}
marg_freq = np.array(
    [
        [0.10, 0.05, 0.02, 0.02],
        [0.05, 0.20, 0.05, 0.02],
        [0.02, 0.05, 0.20, 0.04],
        [0.02, 0.02, 0.04, 0.10],
    ]
)
print("We can represent the table as an array:")
print(marg_freq,"\n")

y_marg = np.sum(marg_freq, axis=axes["x"])
x_marg = np.sum(marg_freq, axis=axes["y"])
print("1a | The marginal frequency function of x is", x_marg)
print("1a | The marginal frequency function of y is", y_marg,"\n")
print("We can see that the matrix is symmetrical. In this case, the conditional freq func of X when Y = 1 is the same as the freq func of Y when X = 1\n")

y_sum_x1 = y_marg[0]
x_sum_y1 = x_marg[0]

x_when_y1 = [round(n / x_sum_y1, 4) for n in marg_freq[0]]
y_when_x1 = [round(row[0] / y_sum_x1, 4) for row in marg_freq]

print("1b | The conditional freq function of y given x = 1 is", y_when_x1)
print("1b | The conditional freq function of x given y = 1 is", x_when_y1)

We can represent the table as an array:
[[0.1  0.05 0.02 0.02]
 [0.05 0.2  0.05 0.02]
 [0.02 0.05 0.2  0.04]
 [0.02 0.02 0.04 0.1 ]] 

1a | The marginal frequency function of x is [0.19 0.32 0.31 0.18]
1a | The marginal frequency function of y is [0.19 0.32 0.31 0.18] 

We can see that the matrix is symmetrical. In this case, the conditional freq func of X when Y = 1 is the same as the freq func of Y when X = 1

1b | The conditional freq function of y given x = 1 is [0.5263, 0.2632, 0.1053, 0.1053]
1b | The conditional freq function of x given y = 1 is [0.5263, 0.2632, 0.1053, 0.1053]
